### ISSUE TITLE
Needs updating for Just Eat September 2016 redesign

### ISSUE THREAD

**Issue by RoyCurtis** [dutts/NomOrVom#20]
In September 2016, [Just Eat apparently redesigned their website and brand](http://i.imgur.com/AcMo7tG.png). As a result, it appears NomOrVom no longer works.
- Error: `Uncaught TypeError: Cannot read property 'insertBefore' of null(anonymous function) @ api.js:89`
- Source of error: https://github.com/dutts/NomOrVom/blob/master/chrome/addon/api.js#L88
- Tested on: Chrome 53.0.2785.116m (64-bit) on Windows 10
- NomOrVom version: 0.18

I've tried to fix this myself, with not much luck. In `api.js`, these selectors need updating:
- Line 88: from `div.restaurants` to `div[data-ft='openRestaurantsList']`
- Line 137: from `h2.name` to `h2[itemprop="name"]`
- Line 138: from `p.address` to `p[itemprop="address"]`

**Comment by dutts** [comment]
Good spot, thanks for reporting this. I'll take a look.

**Comment by dutts** [comment]
From the screenshot it looks like they've moved the restaurant addresses from the main results listing page. This will definitely break NomOrVom which needs addresses to lookup the food hygiene score.
Fortunately I already have similar code to work with Hungry House that has uses a similar design; where the restaurant address is on the linked page rather than the results page.

**Comment by RoyCurtis** [comment]
Very sorry, the screenshot is misleading. The addresses are still present, [albeit in a hidden element](http://i.imgur.com/cBNyUPI.png).

Thanks for taking a look at this!

**Comment by dutts** [comment]
Oh brilliant! I'm at work so haven't had a chance to check out their page source. Will be able to take a look on my train home shortly.

**Comment by dutts** [comment]
Updated to work with new layout, v0.2 submitted to both Firefox and Chrome stores. Both still in the process of validating and publishing as I type, will close this off once they're both live.
Thanks again @RoyCurtis for spotting this.

**Comment by RoyCurtis** [comment]
Awesome! Looking forward to testing the update. Thank you

**Comment by dutts** [comment]
Chrome store updated, Firefox seem to be having server issues; the addon package uploads but just sits on "Validating" forever so may need to wait until tomorrow

**Comment by RoyCurtis** [comment]
Works as expected on Chrome: http://i.imgur.com/Km3lFZH.png

**Comment by dutts** [comment]
Great stuff, apologies for the layout problems, I'll keep working on making it behave itself in this new layout.

**Comment by dutts** [comment]
v0.20 with this bug fix has passed validation and is in both Firefox and Chrome stores.

Thanks again for reporting this.
