### ISSUE TITLE
"foo" popup received for every restaurant on the page

### ISSUE THREAD

**Issue by pbellchambers** [dutts/NomOrVom#5]
When I enter a postcode into just-eat and search, on the results page it gives me a popup message saying "foo" for every restaurant on the page.

If I tell firefox to prevent additional popups being displayed then the results aren't loaded.

![capture2](https://cloud.githubusercontent.com/assets/6773269/6770547/e78c8df0-d0ba-11e4-8902-ce858d836a8e.PNG)

**Comment by dutts** [comment]
Whoops! Forgot to remove this dodgy test code before releasing. I've taken it out and submitted a new version. Thanks for pointing it out.

**Comment by dutts** [comment]
Fixed in v0.12, now live on addon store.

**Comment by pbellchambers** [comment]
All working now. :)
