### ISSUE TITLE
Awaiting inspection shows "AwaitingInspection/5"

### ISSUE THREAD

**Issue by pbellchambers** [dutts/NomOrVom#6]
Just a minor one, looks a bit odd for restaurants that are awaiting inspection:

![capture](https://cloud.githubusercontent.com/assets/6773269/6770554/2ab0da6e-d0bb-11e4-9376-4b48abf3d094.PNG)

**Comment by dutts** [comment]
Good spot! I didn't know they used the food score like that in this case. None of my test searches had an "Awaiting Inspection" in. I'll get that fixed in the next release.

**Comment by dutts** [comment]
Just put a fix in for this (v0.13) submitted to the addon store.

**Comment by dutts** [comment]
v0.13 now live on the store
