### ISSUE TITLE
Create a Chrome port

### ISSUE THREAD

**Issue by dutts** [dutts/NomOrVom#7]

**Comment by gsp8181** [comment]
Here's a small testing version (have attached it to a pull request)

https://github.com/gsp8181/NomOrVom/releases/tag/v0.13-CHROME

**Comment by dutts** [comment]
Chrome version now [here](https://chrome.google.com/webstore/detail/nomorvom/dlddncninpbgmlehociemoojbhhhnmph?hl=en-GB)
